// Generated by CoffeeScript 1.8.0
(function() {
  (function($) {
    return $(function() {
      tinymce.create('tinymce.plugins.Code', {
        init: function(ed, url) {
          ed.addButton('wp-prism-hl-code', {
            title: "Code",
            cmd: "code",
            icon: 'code'
          });
          ed.addShortcut('alt+c', 'Insert [code] shortcode.', 'code');
          return ed.addCommand('code', function() {
            var sel_text, text;
            if (sel_text = ed.selection.getContent()) {
              text = '[code]' + sel_text + '[/code]';
            } else {
              text = '[code][/code]';
            }
            return ed.execCommand('mceInsertContent', 0, text);
          });
        },
        getInfo: function() {
          return [
            {
              longname: "WordPress Prism Highlighter",
              author: "Dmitriy Belyaev",
              authorurl: "http://codemotion.ru",
              infourl: "http://codemotion.ru",
              version: "1.0"
            }
          ];
        }
      });
      return tinymce.PluginManager.add('code', tinymce.plugins.Code);
    });
  })(jQuery);

}).call(this);
